services:
  # 🔹 Frontend React/Next.js client
  - type: web
    name: frontend-client
    env: node
    buildCommand: npm install
    startCommand: npm run dev
    envVars:
      - key: NODE_ENV
        value: development

  # 🔹 Node.js backend with server.ts inside backend/src/
  - type: web
    name: backend-node
    env: node
    buildCommand: cd backend/src && npm install
    startCommand: cd backend/src && npm run dev
    envVars:
      - key: NODE_ENV
        value: development

  # 🔹 Python FastAPI backend (port 8000)
  - type: web
    name: backend-python-fastapi
    env: python
    buildCommand: ./build.sh
    startCommand: uvicorn server:app --host 0.0.0.0 --port 8000
    envVars:
      - key: TESSERACT_CMD
        value: /usr/bin/tesseract

  # 🔹 Second Python FastAPI backend (port 9000)
  - type: web
    name: backend-python2-fastapi
    env: python
    buildCommand: ./build.sh
    startCommand: uvicorn server2:app --host 0.0.0.0 --port 9000
    envVars:
      - key: TESSERACT_CMD
        value: /usr/bin/tesseract
