channels:
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - pymongo
  - python-pptx
  - pillow
  - openpyxl
  - pytesseract
  - pymupdf
  - python-docx
  - pytorch
  - cpuonly
  - lxml           # <-- add this line
  - pip
  - pip:
    - requests
    - transformers
    - accelerate
    - datasets
    - bitsandbytes
    - peft
